### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by xxi511** [vadimkantorov/wigwam#4]
HI I am using [nvidia-docker](https://github.com/NVIDIA/nvidia-docker) , CUDA 7.5 with Cudnn v4
I think I installed most of required package
It show error when I follow the tutorial of ContextLocNet to install torch by wigwam

```shell
root@90f38e9b2db3:/# ldconfig -p | grep cudnn
	libcudnn.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn.so.4
	libcudnn.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcudnn.so
root@90f38e9b2db3:/# find / -name 'cudnn.h'
/usr/include/cudnn.h
root@90f38e9b2db3:/# cd /usr/local/cuda/bin/^C
root@90f38e9b2db3:/# wigwam install torch hdf5 matio protobuf octave -DPATH_TO_NVCC="/usr/local/cuda/bin/nvcc" -DPATH_TO_CUDNN_SO="/usr/lib/x86_64-linux-gnu/libcudnn.so"

Unhandled exception occured!

Please consider filing a bug report at http://github.com/vadimkantorov/wigwam/issues
Please paste the stack trace below into the issue.

==STACK_TRACE_BEGIN==

Traceback (most recent call last):
  File "/dev/fd/63", line 1096, in <module>
  File "/dev/fd/63", line 643, in install
  File "/dev/fd/63", line 265, in default_dict_config
  File "/dev/fd/63", line 280, in find_last_git_commit
  File "/usr/local/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

===STACK_TRACE_END===
```
```shell
# There is no /dev/fd/63, is this could be the problem?
root@90f38e9b2db3:/# cd /dev/fd
root@90f38e9b2db3:/dev/fd# ls
0  1  2  255
```

I don't know how to check which file or directory  is missing
Any suggestion or more detail is needed to provide?
I tried `wigwam install git` is successful
Thanks!!

**Comment by vadimkantorov** [comment]
It seems you are right, the issue is that subprocess can't find git for some reason. Now that you installed git, could you try the following? (to check if git is found fine)
```shell
wigwam in
git --version
```

If this works, try the install command again from within "wigwam in"

**Comment by xxi511** [comment]
Thanks your reply and sorry for reply late. 
I tried to solve the problems I met, it took some time.
But there are some problems I can't solve it.
 
you are right I install `git` by `wigwam`
so I need to use `wigwam in` before continue

problems
1. octave fetch failed, I can use Matlab so it might be ok
```zsh
--2016-12-02 06:53:09--  ftp://ftp.gnu.org/gnu/octave/octave-4.0.3.tar.gz
  (try:20) => '/root/.wigwam/tar/octave.tar.gz'
Connecting to ftp.gnu.org (ftp.gnu.org)|208.118.235.20|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /gnu/octave ... done.
==> SIZE octave-4.0.3.tar.gz ... 22211514
==> PASV ... done.    ==> RETR octave-4.0.3.tar.gz ...
Error in server response, closing control connection.
Giving up.
```

2. wigwam install lua-XXX failed
```zsh
root@9bdf3c68f8fe:~# /\ $ wigwam install lua-rapidjson lua-hdf5 lua-matio lua-loadcaffe lua-xml
5 packages to be installed in the order below:
   lua-xml
lua-rapidjson
  lua-hdf5
 lua-matio
lua-loadcaffe

Updating installation script...  ok [/root/.wigwam/install.generated.sh]
Running installation script now:

lua-xml:
      Fetching...  skipped
   Configuring...  skipped
     Compiling...  skipped
    Installing...  error!

Error occurred while installing [lua-xml]. Press <ENTER> to open [/root/.wigwam/log/lua-xml/install.txt], press <ESC> to quit.
```
```zsh
install: /usr/lib/gcc/x86_64-linux-gnu/4.8/
programs: =/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/bin/
libraries: =/root/.wigwam/prefix/lib64/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/lib64/x86_64-linux-gnu/:/root/.wigwam/prefix/lib64/../lib/:/root/.wigwam/prefix/lib/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/lib/x86_64-linux-gnu/:/root/.wigwam/prefix/lib/../lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:/root/.wigwam/prefix/deb/usr/lib/../lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/../lib/:/usr/local/cuda/bin/../lib64/x86_64-linux-gnu/4.8/:/usr/local/cuda/bin/../lib64/x86_64-linux-gnu/:/usr/local/cuda/bin/../lib64/../lib/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/x86_64-linux-gnu/4.8/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/x86_64-linux-gnu/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/../lib/:/root/.wigwam/prefix/lib64/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/lib64/x86_64-linux-gnu/:/root/.wigwam/prefix/lib64/../lib/:/root/.wigwam/prefix/lib/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/lib/x86_64-linux-gnu/:/root/.wigwam/prefix/lib/../lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:/root/.wigwam/prefix/deb/usr/lib/../lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/../lib/:/usr/local/cuda/bin/../lib64/x86_64-linux-gnu/4.8/:/usr/local/cuda/bin/../lib64/x86_64-linux-gnu/:/usr/local/cuda/bin/../lib64/../lib/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/x86_64-linux-gnu/4.8/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/x86_64-linux-gnu/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/../lib/:/usr/local/cuda/lib64/stubs/x86_64-linux-gnu/4.8/:/usr/local/cuda/lib64/stubs/x86_64-linux-gnu/:/usr/local/cuda/lib64/stubs/../lib/:./x86_64-linux-gnu/4.8/:./x86_64-linux-gnu/:./../lib/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/:/lib/x86_64-linux-gnu/4.8/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/4.8/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/root/.wigwam/prefix/lib64/:/root/.wigwam/prefix/lib/:/root/.wigwam/prefix/deb/usr/lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:/usr/local/cuda/bin/../lib64/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/:/root/.wigwam/prefix/lib64/:/root/.wigwam/prefix/lib/:/root/.wigwam/prefix/deb/usr/lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:/usr/local/cuda/bin/../lib64/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/:/usr/local/cuda/lib64/stubs/:./:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../:/lib/:/usr/lib/

PWD=/root/.wigwam
END_ENV


Error: No results matching query were found.
```
The error seems caused by luarocks, or I might missing some packages needed
(e.g. missing gfortran when install openblas, missing qt4 when install torch)

furthermore, lua seems doesn't exist, is it ok?
```zsh
root@9bdf3c68f8fe:~/.wigwam/src/torch# /\ $ lua -v
bash: lua: command not found
```
Thanks!!

**Comment by vadimkantorov** [comment]
Has torch completed installation fine? You can check it by typing `wigwam status`.

You can disable qt4 dependency of torch by modifying the `$(wigwam path)/Wigwamfile` file and adding `-qt` to make it look like:
```
"torch": {
    "sources": "git cb3ad52",
    "features" : "-qt"
  },
```
After this modification you need to run `wigwam build`, it would try to reinstall packages that failed to install. If you would like to modify the installation script, you can type `wigwam build --dry`, and then modify by hand `$(wigwam path)/.wigwam/build.generated.sh` and then execute this script manually.

Still, Torch install depends on openblas, you would need to install it somehow (for this you may need to comment out the generated `openblas` install from `build.generated.sh`).

lua-\* packages would of course fail to install, since Torch install didn't complete.

Absence of lua is normal, since Torch install failed, even if it completes it would install `luajit` if I'm correct.

**Comment by xxi511** [comment]
HI, I think torch is installed
I installed `qt` and `gfortran` after I know I need them
I used `wigwam clean` first and then `wigwam install torch hdf5 .....etc` again
but lua-* package still failed
```shell
root@9bdf3c68f8fe:~# /\ $ wigwam status
INSTALLED	WIG_NAME            	VERSION   	
        *	autoconf            	v2.69     	
        *	automake            	v1.15     	
        *	cmake               	v3.5.1    	
        *	gnuplot             	v5.0.0    	
        *	hdf5                	v1.8.17   	
        *	libjpeg             	v9b       	
        *	libtool             	v2.4.6    	
         	lua-hdf5            	N/A       	
         	lua-loadcaffe       	N/A       	
         	lua-matio           	N/A       	
         	lua-rapidjson       	N/A       	
         	lua-xml             	N/A       	
        *	m4                  	v1.4.17   	
        *	magma               	v1.6.2    	
        *	matio               	v1.5.8    	
        *	ncurses             	v6.0      	
         	octave              	v4.0.3    	
        *	openblas            	v0.2.19   	
        *	protobuf            	v3.1.0    	
        *	readline            	v6.3      	
        *	torch               	5633c24   	
        *	unzip               	v60       	
        *	zlib                	v1.2.8
```
```
root@9bdf3c68f8fe:~# /\ $ th
 
  ______             __   |  Torch7 
 /_  __/__  ________/ /   |  Scientific computing for Lua. 
  / / / _ \/ __/ __/ _ \  |  Type ? for help 
 /_/  \___/_/  \__/_//_/  |  https://github.com/torch 
                          |  http://torch.ch 
	
th> torch.Tensor{1,2,3}
 1
 2
 3
[torch.DoubleTensor of size 3]
```
```
root@9bdf3c68f8fe:~/.wigwam/prefix/bin# /\ $ ls | grep lua
json2lua
lua2json
luajit
luarocks
luarocks-admin
qlua
```

**Comment by vadimkantorov** [comment]
It's good news Torch / luarocks has installed successfully. Now that we are sure it's the case, could you upload the log / error of `wigwam install lua-hdf5`? Also, you use wigwam by using the alias pointing to this github repo, right?

**Comment by xxi511** [comment]
HI, This is log 
```shell
# /root/.wigwam/log/lua-hdf5/install.txt
BEGIN_ENV
PATH=/root/.wigwam/prefix/bin:/root/.wigwam/prefix/deb/usr/bin:/root/.wigwam/prefix/bin:/root/.wigwam/prefix/deb/usr/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH=/root/.wigwam/prefix/lib64:/root/.wigwam/prefix/lib:/root/.wigwam/prefix/deb/usr/lib:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu:/usr/local/cuda/bin/../lib64:/usr/local/cuda-8.0/targets/x86_64-linux/lib:/root/.wigwam/prefix/lib64:/root/.wigwam/prefix/lib:/root/.wigwam/prefix/deb/usr/lib:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu:/usr/local/cuda/bin/../lib64:/usr/local/cuda-8.0/targets/x86_64-linux/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:
CPATH=/root/.wigwam/prefix/include:/root/.wigwam/prefix/deb/usr/include:/root/.wigwam/prefix/include:/root/.wigwam/prefix/deb/usr/include:
LIBRARY_PATH=/root/.wigwam/prefix/lib64:/root/.wigwam/prefix/lib:/root/.wigwam/prefix/deb/usr/lib:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu:/usr/local/cuda/bin/../lib64:/usr/local/cuda-8.0/targets/x86_64-linux/lib:/root/.wigwam/prefix/lib64:/root/.wigwam/prefix/lib:/root/.wigwam/prefix/deb/usr/lib:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu:/usr/local/cuda/bin/../lib64:/usr/local/cuda-8.0/targets/x86_64-linux/lib:/usr/local/cuda/lib64/stubs:

g++ -print-search-dirs:
install: /usr/lib/gcc/x86_64-linux-gnu/4.8/
programs: =/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/bin/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/bin/
libraries: =/root/.wigwam/prefix/lib64/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/lib64/x86_64-linux-gnu/:/root/.wigwam/prefix/lib64/../lib/:/root/.wigwam/prefix/lib/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/lib/x86_64-linux-gnu/:/root/.wigwam/prefix/lib/../lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:/root/.wigwam/prefix/deb/usr/lib/../lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/../lib/:/usr/local/cuda/bin/../lib64/x86_64-linux-gnu/4.8/:/usr/local/cuda/bin/../lib64/x86_64-linux-gnu/:/usr/local/cuda/bin/../lib64/../lib/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/x86_64-linux-gnu/4.8/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/x86_64-linux-gnu/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/../lib/:/root/.wigwam/prefix/lib64/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/lib64/x86_64-linux-gnu/:/root/.wigwam/prefix/lib64/../lib/:/root/.wigwam/prefix/lib/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/lib/x86_64-linux-gnu/:/root/.wigwam/prefix/lib/../lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:/root/.wigwam/prefix/deb/usr/lib/../lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/4.8/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/../lib/:/usr/local/cuda/bin/../lib64/x86_64-linux-gnu/4.8/:/usr/local/cuda/bin/../lib64/x86_64-linux-gnu/:/usr/local/cuda/bin/../lib64/../lib/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/x86_64-linux-gnu/4.8/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/x86_64-linux-gnu/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/../lib/:/usr/local/cuda/lib64/stubs/x86_64-linux-gnu/4.8/:/usr/local/cuda/lib64/stubs/x86_64-linux-gnu/:/usr/local/cuda/lib64/stubs/../lib/:./x86_64-linux-gnu/4.8/:./x86_64-linux-gnu/:./../lib/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/:/lib/x86_64-linux-gnu/4.8/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/4.8/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/root/.wigwam/prefix/lib64/:/root/.wigwam/prefix/lib/:/root/.wigwam/prefix/deb/usr/lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:/usr/local/cuda/bin/../lib64/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/:/root/.wigwam/prefix/lib64/:/root/.wigwam/prefix/lib/:/root/.wigwam/prefix/deb/usr/lib/:/root/.wigwam/prefix/deb/usr/lib/x86_64-linux-gnu/:/usr/local/cuda/bin/../lib64/:/usr/local/cuda-8.0/targets/x86_64-linux/lib/:/usr/local/cuda/lib64/stubs/:./:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../x86_64-linux-gnu/lib/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../:/lib/:/usr/lib/

PWD=/root/.wigwam
END_ENV


Error: No results matching query were found.
```
This is the paths that I can't find but log contains
```shell
# paths don't exist 
/root/.wigwam/prefix/deb/ # folder exists, but empty
/root/.wigwam/prefix/lib64 # there is no lib64 but there is lib and libexec
/root/.wigwam/prefix/lib/x86_64-linux-gnu/ # there is no x86 folder
```
I just copy it, I think this is ok, right?
```
# follow the website, add alias to ~/.bashrc
alias wigwam='python2.7 <($([ -z "$(which curl)" ] && echo "wget -nv -O -" || echo "curl -sS") https://raw.githubusercontent.com/vadimkantorov/wigwam/master/wigwam.py) --repo https://github.com/vadimkantorov/wigwam/tree/master/wigs'
```

**Comment by vadimkantorov** [comment]
I've fixed the issue (there was a bug in LuarocksWig code). Could you try installing those lua-\star packages in twenty minutes or so (to make sure curl doesn't cache old wigwam code)?

**Comment by xxi511** [comment]
wow, many thanks
The installation is success
